name: "❓ Question or Support Request"
description: Questions and requests for support
title: "[Question]"
labels: ["question"]
body:
  - type: textarea
    id: question_support_request
    attributes:
      label: ❓ Question or Support Request
    validations:
       required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Please provide any additional information that may be relevant or helpful.
